In [48]:
import pandas as pd
import numpy as np
df = pd.read_csv('dulieuxettuyendaihoc.csv')

In [8]:
print(" 10 DÒNG ĐẦU TIÊN ")
print(df.head(10))

 10 DÒNG ĐẦU TIÊN
   STT   T1   L1   H1   S1   V1   X1   D1   N1   T2  ...   X6   D6   N6  GT  \
0    1  7.2  7.3  6.3  7.3  7.0  7.9  7.3  5.5  8.4  ...  6.6  7.6  5.9   F
1    2  5.4  3.9  3.9  4.0  5.4  5.4  5.3  2.8  6.3  ...  6.6  6.1  4.4   M
2    3  5.6  6.8  7.2  7.5  4.3  7.4  5.8  3.2  5.0  ...  7.9  8.1  4.6   M
3    4  6.6  6.4  5.3  6.9  5.4  7.3  6.4  5.8  5.1  ...  7.1  7.3  7.4   M
4    5  6.0  5.0  6.0  7.3  6.5  7.7  7.9  6.1  5.4  ...  6.1  7.5  7.2   M
5    6  9.3  7.6  7.9  8.6  7.0  7.3  7.7  7.9  9.6  ...  5.7  8.0  7.8   M
6    7  2.8  3.9  5.5  6.9  5.0  7.3  4.6  5.2  4.4  ...  6.6  6.0  6.0   F
7    8  8.3  6.0  7.6  5.1  7.5  4.7  5.8  7.2  6.7  ...  7.1  6.8  7.0   F
8    9  6.5  6.3  7.6  6.0  5.5  7.1  6.3  5.0  7.3  ...  9.1  7.9  6.1   F
9   10  7.3  5.9  4.7  7.1  6.7  7.9  6.7  7.7  8.0  ...  6.4  6.1  7.8   F

    DT   KV   DH1   DH2   DH3  KT
0  0.0  2NT  3.25  3.25  4.50  A1
1  0.0    1  6.00  4.00  3.50   C
2  0.0    1  5.00  6.75  4.00   C
3  0.0    1  4.25  4.25  5.25  D1
4  0.0  2NT  4.25  4.50  5.00   A
5  0.0    1  1.50  4.00  6.00  D1
6  0.0    2  6.50  6.75  5.25   C
7  0.0    2  3.75  4.50  4.25  D1
8  0.0    1  3.50  3.50  6.75  D1
9  0.0    1  4.00  4.75  5.50  D1

[10 rows x 56 columns]

In [9]:
print("10 DÒNG CUỐI CÙNG CỦA")
print(df.tail(10))

10 DÒNG CUỐI CÙNG CỦA DỮ LIỆU
    STT   T1   L1   H1   S1   V1   X1   D1   N1   T2  ...   X6   D6   N6  GT  \
90   91  8.1  7.7  9.1  8.5  6.1  8.6  8.8  7.3  8.8  ...  8.3  8.7  7.8   M
91   92  7.8  6.5  6.7  5.4  6.2  4.8  5.9  4.4  8.9  ...  7.2  7.4  7.0   M
92   93  5.0  6.6  6.5  7.2  5.8  6.7  6.4  6.0  6.8  ...  5.9  6.7  5.8   M
93   94  5.2  5.2  6.8  7.9  6.6  8.9  7.6  5.3  6.8  ...  8.7  7.8  5.0   M
94   95  5.8  5.9  7.6  6.1  5.3  8.1  6.1  5.0  6.4  ...  7.3  6.8  5.3   M
95   96  8.6  6.9  7.4  8.8  7.6  5.8  7.3  5.7  8.9  ...  6.3  6.1  6.2   F
96   97  3.7  5.4  6.0  5.1  5.5  3.9  6.1  4.4  4.1  ...  7.9  7.5  4.4   F
97   98  8.8  5.5  7.4  7.7  6.2  7.3  8.1  4.5  9.5  ...  9.6  8.4  5.8   M
98   99  2.7  1.8  3.4  5.3  4.5  7.9  4.9  3.8  2.8  ...  6.6  5.2  5.9   M
99  100  4.1  5.2  4.9  5.3  5.5  5.4  7.2  5.4  4.4  ...  5.6  6.6  5.8   M

     DT   KV   DH1   DH2   DH3  KT
90  0.0    2  6.25  4.00  6.50   A
91  0.0  2NT  4.75  4.75  4.50   A
92  0.0    1  3.25  5.25  4.25   A
93  0.0    1  3.50  4.25  5.00   A
94  0.0    1  4.25  2.50  4.75   A
95  0.0    1  5.25  1.50  6.25   C
96  0.0    1  5.25  3.75  4.75   C
97  0.0  2NT  7.00  8.00  4.00   C
98  0.0    1  5.00  3.50  5.50   C
99  0.0  2NT  5.25  2.50  4.25   C

[10 rows x 56 columns]

In [51]:
df['DT'].fillna(0, inplace=True)
df

/tmp/ipykernel_6673/1359951400.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['DT'].fillna(0, inplace=True)

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,6.6,7.6,5.9,F,0.0,2NT,3.25,3.25,4.50,A1
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.6,6.1,4.4,M,0.0,1,6.00,4.00,3.50,C
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,7.9,8.1,4.6,M,0.0,1,5.00,6.75,4.00,C
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,7.1,7.3,7.4,M,0.0,1,4.25,4.25,5.25,D1
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.1,7.5,7.2,M,0.0,2NT,4.25,4.50,5.00,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,6.3,6.1,6.2,F,0.0,1,5.25,1.50,6.25,C
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,7.9,7.5,4.4,F,0.0,1,5.25,3.75,4.75,C
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,9.6,8.4,5.8,M,0.0,2NT,7.00,8.00,4.00,C
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,6.6,5.2,5.9,M,0.0,1,5.00,3.50,5.50,C
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.6,6.6,5.8,M,0.0,2NT,5.25,2.50,4.25,C

In [13]:
df['T1'].fillna(df['T1'].mean(), inplace=True)
df

/tmp/ipykernel_6673/1000846857.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['T1'].fillna(df['T1'].mean(), inplace=True)

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,6.6,7.6,5.9,F,0.0,2NT,3.25,3.25,4.50,A1
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.6,6.1,4.4,M,0.0,1,6.00,4.00,3.50,C
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,7.9,8.1,4.6,M,0.0,1,5.00,6.75,4.00,C
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,7.1,7.3,7.4,M,0.0,1,4.25,4.25,5.25,D1
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.1,7.5,7.2,M,0.0,2NT,4.25,4.50,5.00,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,6.3,6.1,6.2,F,0.0,1,5.25,1.50,6.25,C
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,7.9,7.5,4.4,F,0.0,1,5.25,3.75,4.75,C
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,9.6,8.4,5.8,M,0.0,2NT,7.00,8.00,4.00,C
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,6.6,5.2,5.9,M,0.0,1,5.00,3.50,5.50,C
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.6,6.6,5.8,M,0.0,2NT,5.25,2.50,4.25,C

In [64]:
print(" SỐ LƯỢNG DỮ LIỆU THIẾU TRƯỚC KHI XỬ LÝ ")
cac_cot_diem = [
    'T1', 'L1', 'H1', 'S1', 'V1', 'X1', 'D1', 'N1',
    'T2', 'L2', 'H2', 'S2', 'V2', 'X2', 'D2', 'N2',
    'T6', 'L6', 'H6', 'S6', 'V6', 'X6', 'D6', 'N6',
    'DH1', 'DH2', 'DH3'
]

df

 SỐ LƯỢNG DỮ LIỆU THIẾU TRƯỚC KHI XỬ LÝ

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,DT,KV,DH1,DH2,DH3,KT,TBM1,TBM2,TBM3,KQXT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,0.0,2NT,3.25,3.25,4.50,A1,7.00,7.54,7.01,0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,0.0,1,6.00,4.00,3.50,C,4.69,5.47,5.07,0
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,0.0,1,5.00,6.75,4.00,C,5.77,5.38,6.04,1
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,0.0,1,4.25,4.25,5.25,D1,6.21,5.20,6.88,0
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,0.0,2NT,4.25,4.50,5.00,A,6.50,6.36,6.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,0.0,1,5.25,1.50,6.25,C,7.43,7.42,6.83,0
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,0.0,1,5.25,3.75,4.75,C,4.93,5.15,6.39,0
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,0.0,2NT,7.00,8.00,4.00,C,7.05,7.84,7.67,1
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,0.0,1,5.00,3.50,5.50,C,4.15,4.72,5.29,0
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,0.0,2NT,5.25,2.50,4.25,C,5.26,5.72,5.85,0

In [58]:
print(" ĐANG TIẾN HÀNH ĐIỀN GIÁ TRỊ MEAN CHO CÁC Ô TRỐNG... ")

# Vòng lặp duyệt qua từng cột điểm số để tính mean và điền khuyết trực tiếp
for cot in cac_cot_diem:
    if cot in df.columns:
        df[cot].fillna(df[cot].mean(), inplace=True)

print(" XỬ LÝ HOÀN TẤT! ")

 ĐANG TIẾN HÀNH ĐIỀN GIÁ TRỊ MEAN CHO CÁC Ô TRỐNG...
 XỬ LÝ HOÀN TẤT!

/tmp/ipykernel_6673/3476933726.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[cot].fillna(df[cot].mean(), inplace=True)

In [65]:
print(" SỐ LƯỢNG DỮ LIỆU THIẾU SAU KHI XỬ LÝ ")
df

 SỐ LƯỢNG DỮ LIỆU THIẾU SAU KHI XỬ LÝ

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,DT,KV,DH1,DH2,DH3,KT,TBM1,TBM2,TBM3,KQXT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,0.0,2NT,3.25,3.25,4.50,A1,7.00,7.54,7.01,0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,0.0,1,6.00,4.00,3.50,C,4.69,5.47,5.07,0
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,0.0,1,5.00,6.75,4.00,C,5.77,5.38,6.04,1
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,0.0,1,4.25,4.25,5.25,D1,6.21,5.20,6.88,0
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,0.0,2NT,4.25,4.50,5.00,A,6.50,6.36,6.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,0.0,1,5.25,1.50,6.25,C,7.43,7.42,6.83,0
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,0.0,1,5.25,3.75,4.75,C,4.93,5.15,6.39,0
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,0.0,2NT,7.00,8.00,4.00,C,7.05,7.84,7.67,1
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,0.0,1,5.00,3.50,5.50,C,4.15,4.72,5.29,0
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,0.0,2NT,5.25,2.50,4.25,C,5.26,5.72,5.85,0

In [62]:
print(" TẠO BIẾN ĐIỂM TRUNG BÌNH MÔN CÁC NĂM ")
df['TBM1'] = (df['T1']*2 + df['L1'] + df['H1'] + df['S1'] + df['V1']*2 + df['X1'] + df['D1'] + df['N1']) / 10
df['TBM2'] = (df['T2']*2 + df['L2'] + df['H2'] + df['S2'] + df['V2']*2 + df['X2'] + df['D2'] + df['N2']) / 10
df['TBM3'] = (df['T6']*2 + df['L6'] + df['H6'] + df['S6'] + df['V6']*2 + df['X6'] + df['D6'] + df['N6']) / 10
df

 TẠO BIẾN ĐIỂM TRUNG BÌNH MÔN CÁC NĂM

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,GT,DT,KV,DH1,DH2,DH3,KT,TBM1,TBM2,TBM3
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,F,0.0,2NT,3.25,3.25,4.50,A1,7.00,7.54,7.01
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,M,0.0,1,6.00,4.00,3.50,C,4.69,5.47,5.07
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,M,0.0,1,5.00,6.75,4.00,C,5.77,5.38,6.04
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,M,0.0,1,4.25,4.25,5.25,D1,6.21,5.20,6.88
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,M,0.0,2NT,4.25,4.50,5.00,A,6.50,6.36,6.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,F,0.0,1,5.25,1.50,6.25,C,7.43,7.42,6.83
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,F,0.0,1,5.25,3.75,4.75,C,4.93,5.15,6.39
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,M,0.0,2NT,7.00,8.00,4.00,C,7.05,7.84,7.67
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,M,0.0,1,5.00,3.50,5.50,C,4.15,4.72,5.29
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,M,0.0,2NT,5.25,2.50,4.25,C,5.26,5.72,5.85

In [32]:
print(" XẾP LOẠI HỌC LỰC CỦA HỌC SINH ")
def xep_loai(tbm):
    if tbm < 5.0: return 'Y'
    elif tbm < 6.5: return 'TB'
    elif tbm < 8.0: return 'K'
    elif tbm < 9.0: return 'G'
    else: return 'XS'

df['XL1'] = df['TBM1'].apply(xep_loai)
df['XL2'] = df['TBM2'].apply(xep_loai)
df['XL3'] = df['TBM3'].apply(xep_loai)
df

 XẾP LOẠI HỌC LỰC CỦA HỌC SINH

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,7.43,7.42,6.83,K,K,K,2.972,2.968,2.732,0
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,4.93,5.15,6.39,Y,TB,TB,1.972,2.060,2.556,0
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,7.05,7.84,7.67,K,K,K,2.820,3.136,3.068,1
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,4.15,4.72,5.29,Y,Y,TB,1.660,1.888,2.116,0
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.26,5.72,5.85,TB,TB,TB,2.104,2.288,2.340,0

In [33]:
print(" QUY ĐỔI SANG THANG ĐIỂM 4 CỦA MỸ ")
df['US_TBM1'] = 4 * (df['TBM1'] / 10)
df['US_TBM2'] = 4 * (df['TBM2'] / 10)
df['US_TBM3'] = 4 * (df['TBM3'] / 10)
df

 QUY ĐỔI SANG THANG ĐIỂM 4 CỦA MỸ

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,7.43,7.42,6.83,K,K,K,2.972,2.968,2.732,0
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,4.93,5.15,6.39,Y,TB,TB,1.972,2.060,2.556,0
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,7.05,7.84,7.67,K,K,K,2.820,3.136,3.068,1
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,4.15,4.72,5.29,Y,Y,TB,1.660,1.888,2.116,0
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.26,5.72,5.85,TB,TB,TB,2.104,2.288,2.340,0

In [63]:
print("KẾT QUẢ TUYỂN SINH")
def xet_tuyen(row):
    khoi = str(row['KT']).strip().upper()
    dh1, dh2, dh3 = row['DH1'], row['DH2'], row['DH3']

    if khoi in ['A', 'A1']: diem_xt = (dh1*2 + dh2 + dh3) / 4
    elif khoi == 'B': diem_xt = (dh1 + dh2*2 + dh3) / 4
    else: diem_xt = (dh1 + dh2 + dh3) / 3

    return 1 if diem_xt >= 5.0 else 0

df['KQXT'] = df.apply(xet_tuyen, axis=1)
df

KẾT QUẢ TUYỂN SINH

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,DT,KV,DH1,DH2,DH3,KT,TBM1,TBM2,TBM3,KQXT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,0.0,2NT,3.25,3.25,4.50,A1,7.00,7.54,7.01,0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,0.0,1,6.00,4.00,3.50,C,4.69,5.47,5.07,0
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,0.0,1,5.00,6.75,4.00,C,5.77,5.38,6.04,1
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,0.0,1,4.25,4.25,5.25,D1,6.21,5.20,6.88,0
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,0.0,2NT,4.25,4.50,5.00,A,6.50,6.36,6.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,0.0,1,5.25,1.50,6.25,C,7.43,7.42,6.83,0
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,0.0,1,5.25,3.75,4.75,C,4.93,5.15,6.39,0
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,0.0,2NT,7.00,8.00,4.00,C,7.05,7.84,7.67,1
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,0.0,1,5.00,3.50,5.50,C,4.15,4.72,5.29,0
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,0.0,2NT,5.25,2.50,4.25,C,5.26,5.72,5.85,0